spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lumExp?createDatabaseIfNotExist=true
    username: admin
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: mike
      password: 1234


  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: boyomichaelbidemi@gmail.com
    password: ybkfsafbwesxfmpc
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true

cloudinary:
  cloud_name: dfsn2ob9s
  api_key: 157327745136222
  api_secret: LgmuK4NwR2Ay6JxK_j0j1-Q_M4o